flaskblog/main/routes.py
from flask import render_template, request, Blueprint, flash, redirect, url_for
from flask_login import login_required, current_user
from flaskblog import db
from flaskblog.models import Post, Favorite, BlogPost, CommunityPost, CommunityReply, User
from flaskblog.forms import CommunityPostForm, CommunityReplyForm

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    
    # First, get Mr Zhukov's recipes (prioritize them)
    zhukov_user = User.query.filter_by(username='Mr Zhukov').first()
    if zhukov_user:
        zhukov_posts = Post.query.filter_by(user_id=zhukov_user.id).order_by(Post.date_posted.desc()).all()
        other_posts = Post.query.filter(Post.user_id != zhukov_user.id).order_by(Post.date_posted.desc()).all()
        # Combine with Zhukov's posts first
        all_posts = zhukov_posts + other_posts
    else:
        all_posts = Post.query.order_by(Post.date_posted.desc()).all()
    
    # Paginate the combined list
    per_page = 12  # Show more recipes on home page
    start = (page - 1) * per_page
    end = start + per_page
    posts = all_posts[start:end]
    
    # Create a simple pagination object
    total_posts = len(all_posts)
    total_pages = (total_posts + per_page - 1) // per_page
    
    class SimplePagination:
        def __init__(self, items, page, per_page, total, total_pages):
            self.items = items
            self.page = page
            self.per_page = per_page
            self.total = total
            self.pages = total_pages
            self.has_next = page < total_pages
            self.has_prev = page > 1
            self.next_num = page + 1 if self.has_next else None
            self.prev_num = page - 1 if self.has_prev else None
    
    posts_paginated = SimplePagination(posts, page, per_page, total_posts, total_pages)
    
    # Get recipe of the day (highest rated or random)
    featured = Post.query.filter(Post.ratings.any()).order_by(db.func.random()).first()
    if not featured:
        featured = Post.query.order_by(db.func.random()).first()
    
    return render_template('home.html', posts=posts_paginated, featured=featured)


@main.route("/search")
def search():
    query = request.args.get('q', '')
    cuisine = request.args.get('cuisine', '')
    difficulty = request.args.get('difficulty', '')
    page = request.args.get('page', 1, type=int)
    
    posts_query = Post.query
    if query:
        posts_query = posts_query.filter(Post.title.contains(query) | Post.ingredients.contains(query) | Post.tags.contains(query))
    if cuisine:
        posts_query = posts_query.filter_by(cuisine=cuisine)
    if difficulty:
        posts_query = posts_query.filter_by(difficulty=difficulty)
    
    posts = posts_query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts, search_query=query, selected_cuisine=cuisine, selected_difficulty=difficulty)


@main.route("/shopping-list")
@login_required
def shopping_list():
    favorites = Favorite.query.filter_by(author=current_user).all()
    favorite_posts = [fav.post for fav in favorites]
    ingredients = []
    for post in favorite_posts:
        ingredients.extend(post.ingredients.split('\n'))
    # Remove duplicates and clean
    unique_ingredients = list(set(ing.strip() for ing in ingredients if ing.strip()))
    return render_template('shopping_list.html', ingredients=unique_ingredients)


@main.route("/about")
def about():
    return render_template('about.html', title='About')


@main.route("/recipes")
def recipes():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=12)
    return render_template('recipes.html', posts=posts, title='Recipes')


@main.route("/smart-search")
def smart_search():
    return render_template('smart_search.html', title='Smart Search')


@main.route("/cultures")
def cultures():
    cuisines = db.session.query(Post.cuisine).distinct().all()
    cuisine_list = [c[0] for c in cuisines if c[0]]
    return render_template('cultures.html', cuisines=cuisine_list, title='Cultures')


@main.route("/challenges")
def challenges():
    return render_template('challenges.html', title='Challenges')


@main.route("/blog")
def blog():
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('blog.html', title='Blog', blog_posts=blog_posts)


@main.route("/blog/<int:blog_id>")
def blog_post(blog_id):
    blog_post = BlogPost.query.get_or_404(blog_id)
    blog_posts = BlogPost.query.order_by(BlogPost.date_posted.desc()).limit(4).all()
    return render_template('blog_post.html', title=blog_post.title, blog_post=blog_post, blog_posts=blog_posts)


@main.route("/community")
@login_required
def community():
    page = request.args.get('page', 1, type=int)
    posts = CommunityPost.query.order_by(CommunityPost.date_posted.desc()).paginate(page=page, per_page=10)
    form = CommunityPostForm()
    return render_template('community.html', title='Community', posts=posts, form=form)


@main.route("/community/new", methods=['GET', 'POST'])
@login_required
def new_community_post():
    form = CommunityPostForm()
    if form.validate_on_submit():
        post = CommunityPost(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.community'))
    return render_template('create_community_post.html', title='New Community Post', form=form, legend='New Community Post')


@main.route("/community/<int:post_id>")
@login_required
def community_post(post_id):
    post = CommunityPost.query.get_or_404(post_id)
    replies = CommunityReply.query.filter_by(post_id=post_id).order_by(CommunityReply.date_posted.asc()).all()
    form = CommunityReplyForm()
    return render_template('community_post.html', title=post.title, post=post, replies=replies, form=form)


@main.route("/community/<int:post_id>/reply", methods=['POST'])
@login_required
def reply_community_post(post_id):
    post = CommunityPost.query.get_or_404(post_id)
    form = CommunityReplyForm()
    if form.validate_on_submit():
        reply = CommunityReply(content=form.content.data, author=current_user, parent_post=post)
        db.session.add(reply)
        db.session.commit()
        flash('Your reply has been posted!', 'success')
    return redirect(url_for('main.community_post', post_id=post_id))


@main.route("/admin")
@login_required
def admin():
    if current_user.username != 'admin':
        abort(403)
    users_count = User.query.count()
    posts_count = Post.query.count()
    comments_count = Comment.query.count()
    return render_template('admin.html', title='Admin', users_count=users_count, posts_count=posts_count, comments_count=comments_count)

flaskblog/recipes/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post, Comment, Rating, Favorite
from flaskblog.recipes.forms import PostForm, CommentForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, ingredients=form.ingredients.data, instructions=form.instructions.data,
                    prep_time=form.prep_time.data, cook_time=form.cook_time.data, servings=form.servings.data,
                    cuisine=form.cuisine.data, difficulty=form.difficulty.data, tags=form.tags.data,
                    author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your recipe has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Recipe',
                           form=form, legend='New Recipe')


@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    form = CommentForm()
    if form.validate_on_submit():
        if not current_user.is_authenticated:
            flash('You must be logged in to comment.', 'danger')
            return redirect(url_for('users.login'))
        comment = Comment(content=form.content.data, author=current_user, post=post)
        db.session.add(comment)
        db.session.commit()
        flash('Your comment has been added!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    return render_template('post.html', title=post.title, post=post, form=form)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.ingredients = form.ingredients.data
        post.instructions = form.instructions.data
        post.prep_time = form.prep_time.data
        post.cook_time = form.cook_time.data
        post.servings = form.servings.data
        post.cuisine = form.cuisine.data
        post.difficulty = form.difficulty.data
        post.tags = form.tags.data
        db.session.commit()
        flash('Your recipe has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.ingredients.data = post.ingredients
        form.instructions.data = post.instructions
        form.prep_time.data = post.prep_time
        form.cook_time.data = post.cook_time
        form.servings.data = post.servings
        form.cuisine.data = post.cuisine
        form.difficulty.data = post.difficulty
        form.tags.data = post.tags
    return render_template('create_post.html', title='Update Recipe',
                           form=form, legend='Update Recipe')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))


@posts.route("/post/<int:post_id>/rate/<int:rating>", methods=['POST'])
@login_required
def rate_post(post_id, rating):
    if rating < 1 or rating > 5:
        abort(400)
    post = Post.query.get_or_404(post_id)
    existing_rating = Rating.query.filter_by(user_id=current_user.id, post_id=post_id).first()
    if existing_rating:
        existing_rating.value = rating
    else:
        new_rating = Rating(value=rating, author=current_user, post=post)
        db.session.add(new_rating)
    db.session.commit()
    flash(f'Rated {rating} stars!', 'success')
    return redirect(url_for('posts.post', post_id=post_id))


@posts.route("/post/<int:post_id>/favorite", methods=['POST'])
@login_required
def favorite_post(post_id):
    post = Post.query.get_or_404(post_id)
    existing_fav = Favorite.query.filter_by(user_id=current_user.id, post_id=post_id).first()
    if existing_fav:
        db.session.delete(existing_fav)
        flash('Removed from favorites!', 'info')
    else:
        fav = Favorite(author=current_user, post=post)
        db.session.add(fav)
        flash('Added to favorites!', 'success')
    db.session.commit()
    return redirect(url_for('posts.post', post_id=post_id))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post, Favorite
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route("/user/<string:username>")
def user_profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    favorites = Favorite.query.filter_by(author=user).all()
    favorite_posts = [fav.post for fav in favorites]
    return render_template('user_profile.html', user=user, posts=posts, favorites=favorite_posts)

flaskblog/templates/admin.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <h1 class="text-center mb-4">Admin Dashboard</h1>
    <div class="row">
        <div class="col-md-4 mb-4">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Total Users</h5>
                    <h2 class="text-primary">{{ users_count }}</h2>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-4">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Total Recipes</h5>
                    <h2 class="text-success">{{ posts_count }}</h2>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-4">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Total Comments</h5>
                    <h2 class="text-info">{{ comments_count }}</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h5>Recent Recipes</h5>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        {% for post in posts.items[:5] %}
                        <li class="list-group-item">
                            <strong>{{ post.title }}</strong> by {{ post.author.username }}
                            <br><small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h5>Admin Actions</h5>
                </div>
                <div class="card-body">
                    <a href="{{ url_for('main.home') }}" class="btn btn-primary btn-block mb-2">View Homepage</a>
                    <a href="{{ url_for('posts.new_post') }}" class="btn btn-success btn-block mb-2">Add New Recipe</a>
                    <a href="{{ url_for('main.recipes') }}" class="btn btn-info btn-block mb-2">Manage Recipes</a>
                    <button class="btn btn-warning btn-block" disabled>Export Data (Coming Soon)</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

flaskblog/templates/community_post.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <!-- Original Post -->
            <div class="card mb-4">
                <div class="card-header bg-primary text-white">
                    <div class="d-flex justify-content-between align-items-center">
                        <h4 class="mb-0">{{ post.title }}</h4>
                        <small>{{ post.date_posted.strftime('%B %d, %Y at %I:%M %p') }}</small>
                    </div>
                </div>
                <div class="card-body">
                    <div class="media mb-3">
                        <img class="rounded-circle mr-3" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" width="50" height="50">
                        <div class="media-body">
                            <h6 class="mt-0">{{ post.author.username }}</h6>
                            <p class="mb-0">{{ post.content }}</p>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Replies -->
            <h5 class="mb-3">{{ replies|length }} Replies</h5>
            {% for reply in replies %}
            <div class="card mb-3">
                <div class="card-body">
                    <div class="media">
                        <img class="rounded-circle mr-3" src="{{ url_for('static', filename='profile_pics/' + reply.author.image_file) }}" width="40" height="40">
                        <div class="media-body">
                            <div class="d-flex justify-content-between align-items-center mb-1">
                                <h6 class="mt-0 mb-0">{{ reply.author.username }}</h6>
                                <small class="text-muted">{{ reply.date_posted.strftime('%b %d, %Y at %I:%M %p') }}</small>
                            </div>
                            <p class="mb-0">{{ reply.content }}</p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

            <!-- Reply Form -->
            {% if current_user %}
            <div class="card">
                <div class="card-header bg-light">
                    <h6 class="mb-0">Post a Reply</h6>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ url_for('main.reply_community_post', post_id=post.id) }}">
                        {{ form.hidden_tag() }}
                        <div class="form-group">
                            {{ form.content.label(class="form-control-label") }}
                            {{ form.content(class="form-control", rows=3) }}
                            {% if form.content.errors %}
                                {% for error in form.content.errors %}
                                    <small class="text-danger">{{ error }}</small>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.submit(class="btn btn-primary") }}
                        </div>
                    </form>
                </div>
            </div>
            {% else %}
            <div class="alert alert-info">
                <i class="fas fa-info-circle"></i> <a href="{{ url_for('users.login') }}">Login</a> to join the discussion!
            </div>
            {% endif %}
        </div>

        <div class="col-lg-4">
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title">Community Guidelines</h5>
                    <ul class="list-unstyled small">
                        <li class="mb-2">🍳 Share your cooking experiences</li>
                        <li class="mb-2">🤝 Be respectful to fellow members</li>
                        <li class="mb-2">📸 Post photos of your creations</li>
                        <li class="mb-2">❓ Ask questions about recipes</li>
                        <li class="mb-2">💡 Give and receive cooking tips</li>
                        <li class="mb-0">🌟 Celebrate culinary successes!</li>
                    </ul>
                </div>
            </div>

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Quick Links</h5>
                    <ul class="list-unstyled">
                        <li class="mb-2"><a href="{{ url_for('main.community') }}" class="text-decoration-none">← Back to Community</a></li>
                        <li class="mb-2"><a href="{{ url_for('main.new_community_post') }}" class="text-decoration-none">Start New Discussion</a></li>
                        <li class="mb-2"><a href="{{ url_for('main.recipes') }}" class="text-decoration-none">Browse Recipes</a></li>
                        <li class="mb-0"><a href="{{ url_for('main.blog') }}" class="text-decoration-none">Read Blog</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

flaskblog/templates/cultures.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <h1 class="text-center mb-4">Explore World Cuisines</h1>
    <p class="text-center mb-5">Discover authentic recipes from different cultures around the world. From Italian pasta to Korean kimchi, explore the rich diversity of global cuisine.</p>
    <div class="row">
        {% for cuisine in cuisines %}
        <div class="col-md-4 mb-4">
            <div class="card h-100 shadow-sm">
                <div class="card-body text-center">
                    <h5 class="card-title">{{ cuisine }}</h5>
                    <p class="card-text">Explore delicious {{ cuisine.lower() }} recipes shared by our community.</p>
                    <a href="{{ url_for('main.search', cuisine=cuisine) }}" class="btn btn-primary">View {{ cuisine }} Recipes</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      {% if post.image_file %}
        <img src="{{ url_for('static', filename='recipe_pics/' + post.image_file) }}" alt="Recipe Image" class="img-fluid mb-3">
      {% endif %}
      <div class="recipe-details">
        <p><strong>Prep Time:</strong> {{ post.prep_time or 'N/A' }}</p>
        <p><strong>Cook Time:</strong> {{ post.cook_time or 'N/A' }}</p>
        <p><strong>Servings:</strong> {{ post.servings or 'N/A' }}</p>
        <p><strong>Cuisine:</strong> {{ post.cuisine or 'N/A' }}</p>
        <p><strong>Difficulty:</strong> {{ post.difficulty or 'N/A' }}</p>
        <p><strong>Tags:</strong> {{ post.tags or 'N/A' }}</p>
        <p><strong>Rating:</strong> {{ post.average_rating }}/5 stars ({{ post.ratings|length }} reviews)</p>
      </div>
      {% if current_user %}
        <div class="mb-3">
          <strong>Rate this recipe:</strong>
          {% for i in range(1, 6) %}
            <form action="{{ url_for('posts.rate_post', post_id=post.id, rating=i) }}" method="post" style="display: inline;">
              <button type="submit" class="btn btn-link p-0">
                {% if i <= post.average_rating %}
                  <i class="fas fa-star text-warning"></i>
                {% else %}
                  <i class="far fa-star text-warning"></i>
                {% endif %}
              </button>
            </form>
          {% endfor %}
        </div>
        <form action="{{ url_for('posts.favorite_post', post_id=post.id) }}" method="post" style="display: inline;">
          <button type="submit" class="btn btn-outline-danger">
            {% if current_user.favorites|selectattr('post_id', 'equalto', post.id)|list %}
              <i class="fas fa-heart"></i> Remove from Favorites
            {% else %}
              <i class="far fa-heart"></i> Add to Favorites
            {% endif %}
          </button>
        </form>
      {% endif %}
      <h4>Ingredients</h4>
      <p class="article-content">{{ post.ingredients }}</p>
      <h4>Instructions</h4>
      <p class="article-content">{{ post.instructions }}</p>
      <div class="mt-3">
        <h5>Share this recipe:</h5>
        <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.url }}" class="btn btn-primary">Facebook</a>
        <a href="https://twitter.com/intent/tweet?url={{ request.url }}&text={{ post.title }}" class="btn btn-info">Twitter</a>
      </div>
    </div>
  </article>

  <div class="content-section">
    <h4>Comments</h4>
    {% for comment in post.comments %}
      <div class="media mb-3">
        <img class="rounded-circle mr-3" src="{{ url_for('static', filename='profile_pics/' + comment.author.image_file) }}" width="40" height="40">
        <div class="media-body">
          <div class="article-metadata">
            <a href="{{ url_for('users.user_posts', username=comment.author.username) }}">{{ comment.author.username }}</a>
            <small class="text-muted">{{ comment.date_posted.strftime('%Y-%m-%d %H:%M') }}</small>
          </div>
          <p>{{ comment.content }}</p>
        </div>
      </div>
    {% endfor %}
    {% if current_user %}
      <form method="POST" action="">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.content.label(class="form-control-label") }}
          {{ form.content(class="form-control") }}
        </div>
        <div class="form-group">
          {{ form.submit(class="btn btn-outline-info") }}
        </div>
      </form>
    {% else %}
      <p><a href="{{ url_for('users.login') }}">Login</a> to comment.</p>
    {% endif %}
  </div>

  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Recipe?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}